// GOOBY V4/G51 — music registry (PLAN4 §B2, §C-SYS1.1/1.2): the committed
// build-time manifest (src/data/musicManifest.json, generated by
// scripts/gen-music-manifest.mjs) turned into RADIO STATIONS and CONTEXT
// lookups. Pure data module — no DOM/three imports, node-testable.
//
//   getTracks()            → all manifest tracks (frozen rows)
//   trackById(id)          → row | null
//   getStations(tracks?)   → §C-SYS1.2 station rows with trackIds + count
//                            (stations with zero tracks don't render)
//   stationTrackIds(id)    → member ids of one station (stingers excluded)
//   trackFor(context, opts)→ the real music track for a scene/room/game
//                            context (owner folder convention — see below),
//                            or null when the manifest has none
//   coverFor(track, stationId?) → cover path relative to /assets/ with the
//                            §C-SYS1.6 fallback chain (track cover → station
//                            cover → covers/cover_default.png)
//
// Station table (§C-SYS1.2 — ids are FROZEN, save validate() coerces unknown
// radio.station values to 'bordmusik'):
//   bordmusik  all builtin CC0 tracks (§C-SYS1.7 — never empty)
//   gooby-fm   owner `Radio` category (incl. level-locked folder tracks —
//              the QUEUE filters by unlockLevel, the list shows lock badges)
//   recap-fm   owner `Recap` tracks + the builtin recap fallback
//   game-fm    owner `Game` tracks (per-game themes also play via trackFor)
//   alle       every non-stinger track incl. Room/Location context tracks
//
// `Stinger` tracks NEVER join a station (§C-SYS1.2) — one-shot cues.
//
// Context tokens (trackFor): 'room:kitchen|living|bathroom|bedroom|garden',
// 'game:<minigameId>', 'location:city|shop|vet', 'arcade' — plus the
// musicDirector context aliases 'home'→room:living, 'garden'→room:garden,
// 'city'→location:city, 'shop'→location:shop (IKEA). The bedroom has Awake/
// Sleeping variants: trackFor('room:bedroom', { sleeping: true }).

import manifest from '../data/musicManifest.json' with { type: 'json' };

/** §C-SYS1.6 runtime fallback cover (committed in the ART-GATE-1 pre-wave). */
export const DEFAULT_COVER = 'GoobyMusic/covers/cover_default.png';

/**
 * §C-SYS1.2 station table (frozen ids + bilingual labels as data — station
 * names are data-driven content like food/outfit names; G52's v4-radio
 * strings module also carries `radio.station.<id>` keys and wins when
 * translated). unlockLevel gates the STATION chip (G52 UI); per-track
 * unlockLevel gates the queue.
 * @type {ReadonlyArray<{id: string, nameKey: string, labelEN: string,
 *   labelDE: string, unlockLevel: number, cover: string}>}
 */
export const STATION_DEFS = Object.freeze([
  Object.freeze({ id: 'bordmusik', nameKey: 'radio.station.bordmusik', labelEN: 'On-board Tunes', labelDE: 'Bordmusik', unlockLevel: 1, cover: 'GoobyMusic/covers/cover_station_cozy.png' }),
  Object.freeze({ id: 'gooby-fm', nameKey: 'radio.station.gooby-fm', labelEN: 'Gooby FM', labelDE: 'Gooby FM', unlockLevel: 1, cover: 'GoobyMusic/covers/cover_station_garten.png' }),
  Object.freeze({ id: 'recap-fm', nameKey: 'radio.station.recap-fm', labelEN: 'Epic', labelDE: 'Episch', unlockLevel: 5, cover: 'GoobyMusic/covers/cover_station_nacht.png' }),
  Object.freeze({ id: 'game-fm', nameKey: 'radio.station.game-fm', labelEN: 'Arcade', labelDE: 'Arcade', unlockLevel: 8, cover: 'GoobyMusic/covers/cover_station_arcade.png' }),
  Object.freeze({ id: 'alle', nameKey: 'radio.station.alle', labelEN: 'Everything', labelDE: 'Alles', unlockLevel: 1, cover: DEFAULT_COVER }),
]);

/** @type {ReadonlyArray<string>} the valid station ids, §C-SYS1.2 order */
export const STATION_IDS = Object.freeze(STATION_DEFS.map((s) => s.id));

/** §B2.1: sub-10-second files are one-shot stingers. */
export const STINGER_MAX_SEC = 10;

/** @typedef {{id: string, file: string, category: string, title: string,
 *   source: string, durationSec: number, gainTrim: number,
 *   unlockLevel: number, context: string|null, variant: string|null,
 *   cover: string|null, beats: string|null}} Track */

/** @type {ReadonlyArray<Track>} */
const TRACKS = Object.freeze(
  (Array.isArray(manifest?.tracks) ? manifest.tracks : []).map((t) => Object.freeze({ ...t }))
);

const BY_ID = new Map(TRACKS.map((t) => [t.id, t]));

/** @returns {ReadonlyArray<Track>} every manifest track (sorted by id) */
export function getTracks() {
  return TRACKS;
}

/**
 * @param {string} id
 * @returns {Track|null}
 */
export function trackById(id) {
  return BY_ID.get(id) ?? null;
}

/**
 * §C-SYS1.2: stinger tracks never join a station.
 * @param {Track} track
 */
export function isStinger(track) {
  return track.category === 'Stinger' ||
    (Number(track.durationSec) > 0 && Number(track.durationSec) < STINGER_MAX_SEC);
}

/**
 * §C-SYS1.2 station membership rule.
 * @param {Track} track @param {string} stationId
 * @returns {boolean}
 */
export function trackBelongsTo(track, stationId) {
  if (isStinger(track)) return false;
  switch (stationId) {
    case 'alle': return true;
    case 'bordmusik': return track.source === 'builtin' && track.category !== 'Recap';
    case 'gooby-fm': return track.category === 'Radio';
    case 'recap-fm': return track.category === 'Recap';
    case 'game-fm': return track.category === 'Game';
    default: return false;
  }
}

/**
 * Member track ids of one station (§C-SYS1.2 — level-locked tracks are
 * INCLUDED here; the queue logic filters them per player level).
 * @param {string} stationId
 * @param {ReadonlyArray<Track>} [tracks]
 * @returns {string[]}
 */
export function stationTrackIds(stationId, tracks = TRACKS) {
  return tracks.filter((t) => trackBelongsTo(t, stationId)).map((t) => t.id);
}

/**
 * §C-SYS1.2 station rows for the radio UI: fixed defs + per-station track
 * lists; stations with zero tracks are dropped (day one every row has
 * tracks — bordmusik ships 13, recap-fm 3, alle everything).
 * @param {ReadonlyArray<Track>} [tracks]
 * @returns {Array<{id: string, nameKey: string, labelEN: string,
 *   labelDE: string, unlockLevel: number, cover: string,
 *   trackIds: string[], count: number}>}
 */
export function getStations(tracks = TRACKS) {
  const out = [];
  for (const def of STATION_DEFS) {
    const trackIds = stationTrackIds(def.id, tracks);
    if (trackIds.length === 0) continue;
    out.push({ ...def, trackIds, count: trackIds.length });
  }
  return out;
}

// ---------------------------------------------------------------------------
// trackFor(context) — real music behind scene/room/game/location contexts
// ---------------------------------------------------------------------------

/**
 * musicDirector context aliases → owner folder context tokens. 'home' plays
 * the living-room track (roomManager refines per room via the radio engine's
 * room hook); 'shop' is the IKEA trip per the owner folder convention.
 * @type {Readonly<Record<string, string>>}
 */
export const CONTEXT_ALIASES = Object.freeze({
  home: 'room:living',
  garden: 'room:garden',
  city: 'location:city',
  shop: 'location:shop',
  vet: 'location:vet',
  arcade: 'arcade',
});

/**
 * Resolve the real music track for a context (owner folder convention).
 * @param {string} context 'room:<id>'|'game:<id>'|'location:<id>'|'arcade'
 *   or a musicDirector alias ('home'|'garden'|'city'|'shop')
 * @param {{sleeping?: boolean, tracks?: ReadonlyArray<Track>}} [opts]
 *   sleeping picks the bedroom Sleeping variant (default the Awake one)
 * @returns {Track|null} null when the manifest carries no such track —
 *   callers fall back to the §B2.4-v3 jingle medley
 */
export function trackFor(context, opts = {}) {
  const tracks = opts.tracks ?? TRACKS;
  const token = CONTEXT_ALIASES[context] ?? String(context ?? '');
  if (!token) return null;
  const matches = tracks.filter((t) => t.context === token && !isStinger(t));
  if (matches.length === 0) return null;
  if (token === 'room:bedroom') {
    const wantVariant = opts.sleeping ? 'sleeping' : 'awake';
    const variant = matches.find((t) => t.variant === wantVariant) ??
      matches.find((t) => t.variant == null) ?? matches[0];
    return variant ?? null;
  }
  return matches[0];
}

/**
 * §C-SYS1.6 cover fallback chain: track cover → station cover → default.
 * @param {Track|string|null} trackOrId
 * @param {string} [stationId]
 * @returns {string} cover path relative to /assets/
 */
export function coverFor(trackOrId, stationId) {
  const track = typeof trackOrId === 'string' ? trackById(trackOrId) : trackOrId;
  if (track?.cover) return track.cover;
  const station = STATION_DEFS.find((s) => s.id === stationId);
  return station?.cover ?? DEFAULT_COVER;
}

export default {
  STATION_DEFS, STATION_IDS, DEFAULT_COVER, CONTEXT_ALIASES,
  getTracks, trackById, isStinger, trackBelongsTo, stationTrackIds,
  getStations, trackFor, coverFor,
};
